<a href="https://colab.research.google.com/github/Derrick287/Data-Analysis-with-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>1. Introduction</h2>

<h2>1.1 Array Creation</h2>

In [2]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Initialize array with zeros
zeros_arr = np.zeros((3, 3))  # 3x3 array of zeros

# Initialize array with ones
ones_arr = np.ones((2, 4))  # 2x4 array of ones

# Create an array with a range of values
range_arr = np.arange(0, 10, 2)  # array([0, 2, 4, 6, 8])

# Create an array with random values
random_arr = np.random.rand(3, 3)  # 3x3 array of random values between 0 and 1


<h2>1.2 Indexing:</h2>

<h3>1.2.1 Indexing: Accessing elements in a 1D array:</h3>

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])  # 1
print(arr[3])  # 4


1
4


<h3>1.2.2 Indexing: Accessing elements in a 2D array</h3>

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 1])  # 2
print(arr[1, 2])  # 6

2
6


<h3>1.2.3 Indexing:Boolean indexing (using a boolean mask):</h3>

In [6]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2

print(arr[mask])  # [3, 4, 5]

[3 4 5]


<h2>1.3 Slicing:</h2>

<h3>1.3.1 Slicing: Slicing a 1D array</h3>

In [7]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])  # [2, 3, 4]
print(arr[:3])   # [1, 2, 3]
print(arr[2:])   # [3, 4, 5]


[2 3 4]
[1 2 3]
[3 4 5]


<h3>1.3.2 Slicing: Slicing a 2D array</h3>

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[1:3, 0:2])
# [[4, 5]
#  [7, 8]]

print(arr[:, 1])  # [2, 5, 8]

[[4 5]
 [7 8]]
[2 5 8]


<h3>1.3.3 Slicing: Assigning values using slicing</h3>


In [9]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 10

print(arr)  # [1, 10, 10, 10, 5]


[ 1 10 10 10  5]


<h2>1.4 Array attributes and methods</h2>

<h3>Array Attributes:</h3>

<b>ndarray.shape</b>: Returns the dimensions of the array as a tuple. For a 2D array, it returns (rows, columns).<br>
<b>ndarray.size</b>: Returns the total number of elements in the array.<br>
<b>ndarray.dtype</b>: Returns the data type of the elements in the array.<br>
<b>ndarray.ndim</b>: Returns the number of dimensions (axes) of the array.<br>
<b>ndarray.itemsize</b>: Returns the size (in bytes) of each element in the array.<br>
<h3>Array Methods:</h3>

<b>ndarray.reshape(new_shape)</b>: Returns a new array with a different shape. The new_shape argument should be a tuple specifying the desired dimensions.<br>
<b>ndarray.transpose()</b>: Returns a new array with axes transposed. It is equivalent to calling ndarray.T.<br>
<b>ndarray.flatten()</b>: Returns a new 1D array containing a copy of the elements of the original array. The returned array is always a copy, even if the original array was 1D.<br>
<b>ndarray.max(), ndarray.min()</b>: Returns the maximum or minimum element in the array.<br>
<b>ndarray.mean(), ndarray.sum()</b>: Returns the mean or sum of the elements in the array.<br>
<b>ndarray.argmax(), ndarray.argmin()</b>: Returns the indices of the maximum or minimum element in the array.<br>
<b>ndarray.sort()</b>: Sorts the elements of the array along a specified axis.<br>
<b>ndarray.concatenate(arrays, axis=None)</b>: Concatenates multiple arrays along the specified axis.<br>

In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)         # (2, 3)
print(arr.size)          # 6
print(arr.dtype)         # int64
print(arr.ndim)          # 2
print(arr.itemsize)      # 8 (bytes)

reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr)      # [[1 2]
                         #  [3 4]
                         #  [5 6]]

transposed_arr = arr.transpose()
print(transposed_arr)    # [[1 4]
                         #  [2 5]
                         #  [3 6]]

flattened_arr = arr.flatten()
print(flattened_arr)     # [1 2 3 4 5 6]

print(arr.max())         # 6
print(arr.min())         # 1
print(arr.mean())        # 3.5
print(arr.sum())         # 21

sorted_arr = arr.sort(axis=0)
print(arr)               # [[1 2 3]
                         #  [4 5 6]]


(2, 3)
6
int64
2
8
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
6
1
3.5
21
[[1 2 3]
 [4 5 6]]


<h1>2. NumPy Array Operations</h1>

<h2>2.1. Basic array operations: arithmetic, logical, and comparison operations</h2>

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Arithmetic Operations
addition = arr1 + arr2
print(addition)           # [5 7 9]

multiplication = arr1 * arr2
print(multiplication)     # [4 10 18]

exponentiation = np.exp(arr1)
print(exponentiation)     # [2.71828183 7.3890561  20.08553692]

# Logical Operations
logical_and = arr1 > 1
print(logical_and)        # [False  True  True]

logical_or = arr1 < 2
print(logical_or)         # [ True False False]

logical_not = ~logical_and
print(logical_not)        # [ True False False]

# Comparison Operations
equality = arr1 == arr2
print(equality)           # [False False False]

greater_than = arr1 > arr2
print(greater_than)       # [False False False]

less_than_or_equal_to = arr1 <= arr2
print(less_than_or_equal_to)  # [ True  True  True]


[5 7 9]
[ 4 10 18]
[ 2.71828183  7.3890561  20.08553692]
[False  True  True]
[ True False False]
[ True False False]
[False False False]
[False False False]
[ True  True  True]


<h1>2.2. Broadcasting and vectorization</h2>

<h3>2.2.1 Broadcasting</h3>


In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

result = a + b
print(result)
# [[5 6 7]
#  [6 7 8]
#  [7 8 9]]


[[5 6 7]
 [6 7 8]
 [7 8 9]]


<h3>2.2.3. Vectorization</h3>

In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a * b
print(result)  # [4 10 18]


[ 4 10 18]


<h2>2.3. Array reshaping and resizing</h2>

<h3>2.3.1. Reshaping:</h3>

<b>ndarray.reshape(new_shape)</b>: Returns a new array with a different shape, without changing the original array. The new_shape argument should be a tuple specifying the desired dimensions.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


<b>ndarray.resize(new_shape)</b>: Changes the shape of the array in-place, modifying the original array. If the new shape is larger than the original shape, the array will be filled with repeated copies of the original data. If the new shape is smaller, elements will be discarded.

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr.resize((2, 4))
print(arr)
# [[1 2 3 4]
#  [5 6 1 2]]


[[1 2 3 4]
 [5 6 0 0]]


<h3>2.3.1. Reshaping with Specified Size:</h3>

<b>ndarray.reshape(new_shape)</b>: Similar to the <b>reshape()</b> method, but you can specify one of the dimensions as -1, and NumPy will automatically calculate the correct size based on the other dimensions.

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape((2, -1))
print(reshaped_arr)
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


<b>np.reshape(arr, new_shape)</b>: A function alternative to the reshape() method.

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, -1))
print(reshaped_arr)
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


<h2>2.4. Stacking and splitting arrays</h2>

<h3>2.4.1. Stacking Arrays:</h3>

<b>np.concatenate(arrays, axis=0)</b>: Concatenates multiple arrays along the specified axis. The arrays must have the same shape along the other dimensions.

In [18]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked = np.concatenate((arr1, arr2))
print(stacked)  # [1 2 3 4 5 6]


[1 2 3 4 5 6]


<b>np.vstack(tup)</b>: Stacks arrays vertically (row-wise) to form a new array.

In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked = np.vstack((arr1, arr2))
print(stacked)
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


<b>np.hstack(tup)</b>: Stacks arrays horizontally (column-wise) to form a new array.

In [21]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked = np.hstack((arr1, arr2))
print(stacked)  # [1 2 3 4 5 6]


[1 2 3 4 5 6]


<h3>2.4.2. Splitting Arrays:</h3>

<b>np.split(arr, indices_or_sections, axis=0)</b>: Splits an array into multiple sub-arrays along the specified axis. The indices_or_sections argument specifies either the indices at which to split the array or the number of equally sized sub-arrays to create.

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

splitted = np.split(arr, 3)
print(splitted)
# [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]


<b>np.vsplit(arr, indices_or_sections)</b>: Splits an array vertically (row-wise) into multiple sub-arrays.

In [23]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

splitted = np.vsplit(arr, 3)
print(splitted)
# [array([[1, 2, 3]]),
#  array([[4, 5, 6]]),
#  array([[7, 8, 9]])]


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


<b>np.hsplit(arr, indices_or_sections)</b>: Splits an array horizontally (column-wise) into multiple sub-arrays.

In [24]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

splitted = np.hsplit(arr, 3)
print(splitted)
# [array([[1],
#         [4],
#         [7]]),
#  array([[2],
#         [5],
#         [8]]),
#  array([[3],
#         [6],
#         [9]])]


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
